language: node_js
dist: trusty
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - >-
    npm run update-types && git diff --exit-code || (echo -e
    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
    update-types".' && false)
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi